# Generated by Django 3.0.3 on 2020-02-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_n_registration_app', '0006_auto_20200220_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('found', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_by_whom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to='login_n_registration_app.User')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='login_n_registration_app.User')),
            ],
        ),
    ]
