# Generated by Django 3.0.3 on 2020-02-22 22:02

from django.db import migrations, models
import login_n_registration_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_n_found_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='campus',
            field=models.CharField(choices=[(login_n_registration_app.models.Campus['arlington'], 'Arlington, VA'), (login_n_registration_app.models.Campus['boise'], 'Boise, ID'), (login_n_registration_app.models.Campus['chicago'], 'Chicago, IL'), (login_n_registration_app.models.Campus['dallas'], 'Dallas, TX'), (login_n_registration_app.models.Campus['los_angeles'], 'Los Angeles, CA'), (login_n_registration_app.models.Campus['oakland'], 'Oakland, CA'), (login_n_registration_app.models.Campus['orange_county'], 'Orange County, CA'), (login_n_registration_app.models.Campus['seatle'], 'Seatle, WA'), (login_n_registration_app.models.Campus['silicon_valley'], 'Silicon Valley, CA'), (login_n_registration_app.models.Campus['tulsa'], 'Tulsa, OK')], max_length=255, null=True),
        ),
    ]
