# Generated by Django 3.0.3 on 2020-02-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_n_registration_app', '0006_auto_20200220_2038'),
        ('lost_n_found_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='found_by_whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to='login_n_registration_app.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='login_n_registration_app.User'),
        ),
    ]
