# Generated by Django 3.0.3 on 2020-02-22 19:50

from django.db import migrations, models
import lost_n_found_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_n_found_app', '0002_auto_20200220_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=lost_n_found_app.models.path_and_rename),
        ),
    ]
