# Generated by Django 3.0.3 on 2020-02-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_n_registration_app', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
    ]
