# Generated by Django 3.0.3 on 2020-02-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_n_registration_app', '0003_remove_user_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
