# Generated by Django 3.0.3 on 2020-02-22 20:34

from django.db import migrations, models
import login_n_registration_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_n_registration_app', '0006_auto_20200220_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(choices=[(login_n_registration_app.models.Campus['arlington'], 'Arlington, VA'), (login_n_registration_app.models.Campus['boise'], 'Boise, ID'), (login_n_registration_app.models.Campus['chicago'], 'Chicago, IL'), (login_n_registration_app.models.Campus['dallas'], 'Dallas, TX'), (login_n_registration_app.models.Campus['los_angeles'], 'Los Angeles, CA'), (login_n_registration_app.models.Campus['oakland'], 'Oakland, CA'), (login_n_registration_app.models.Campus['orange_county'], 'Orange County, CA'), (login_n_registration_app.models.Campus['seatle'], 'Seatle, WA'), (login_n_registration_app.models.Campus['silicon_valley'], 'Silicon Valley, CA'), (login_n_registration_app.models.Campus['tulsa'], 'Tulsa, OK')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[(login_n_registration_app.models.Level['instructor'], 'Instructor'), (login_n_registration_app.models.Level['student'], 'Student')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
