# Generated by Django 3.0.3 on 2020-02-22 22:02

from django.db import migrations, models
import login_n_registration_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_n_registration_app', '0007_auto_20200222_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=login_n_registration_app.models.path_and_rename),
        ),
    ]
